## auth=oauth|apikey|signV4

## google/gemini-2.5-flash
google/gemini-2.5-flash.primary.provider=google
google/gemini-2.5-flash.primary.model=google/gemini-2.5-flash
google/gemini-2.5-flash.primary.auth=oauth
google/gemini-2.5-flash.primary.hostname=aiplatform.googleapis.com
google/gemini-2.5-flash.primary.url=/v1/projects/YOUR_PROJECT_ID/locations/global/endpoints/openapi/chat/completions

google/gemini-2.5-flash.fallback.provider=google
google/gemini-2.5-flash.fallback.model=google/gemini-2.5-flash
google/gemini-2.5-flash.fallback.auth=oauth
google/gemini-2.5-flash.fallback.hostname=us-east1-aiplatform.googleapis.com
google/gemini-2.5-flash.fallback.url=/v1beta1/projects/YOUR_PROJECT_ID/locations/us-east1/endpoints/openapi/chat/completions


## google/gemini-3-flash-preview
google/gemini-3-flash-preview.primary.provider=google
google/gemini-3-flash-preview.primary.model=google/gemini-3-flash-preview
google/gemini-3-flash-preview.primary.auth=oauth
google/gemini-3-flash-preview.primary.hostname=aiplatform.googleapis.com
google/gemini-3-flash-preview.primary.url=/v1/projects/YOUR_PROJECT_ID/locations/global/endpoints/openapi/chat/completions

google/gemini-3-flash-preview.fallback.provider=google
google/gemini-3-flash-preview.fallback.model=google/gemini-3-flash-preview
google/gemini-3-flash-preview.fallback.auth=oauth
google/gemini-3-flash-preview.fallback.hostname=aiplatform.googleapis.com
google/gemini-3-flash-preview.fallback.url=/v1/projects/YOUR_PROJECT_ID/locations/global/endpoints/openapi/chat/completions


## google/gemini-3.1-pro-preview
google/gemini-3.1-pro-preview.primary.provider=google
google/gemini-3.1-pro-preview.primary.model=google/gemini-3.1-pro-preview
google/gemini-3.1-pro-preview.primary.auth=oauth
google/gemini-3.1-pro-preview.primary.hostname=aiplatform.googleapis.com
google/gemini-3.1-pro-preview.primary.url=/xxxv1/projects/YOUR_PROJECT_ID/locations/global/endpoints/openapi/chat/completions

google/gemini-3.1-pro-preview.fallback.provider=azure
google/gemini-3.1-pro-preview.fallback.model=gpt-4.1-mini
google/gemini-3.1-pro-preview.fallback.auth=apikey
google/gemini-3.1-pro-preview.fallback.hostname=YOUR_AZURE_HOSTNAME
google/gemini-3.1-pro-preview.fallback.url=/openai/deployments/gpt-4.1-mini/chat/completions?api-version=2025-01-01-preview
google/gemini-3.1-pro-preview.fallback.apikey=YOUR_API_KEY


## google/gemini-3.1-flash-lite-preview
google/gemini-3.1-flash-lite-preview.primary.provider=google
google/gemini-3.1-flash-lite-preview.primary.model=google/gemini-3.1-flash-lite-preview
google/gemini-3.1-flash-lite-preview.primary.auth=oauth
google/gemini-3.1-flash-lite-preview.primary.hostname=aiplatform.googleapis.com
google/gemini-3.1-flash-lite-preview.primary.url=/v1/projects/YOUR_PROJECT_ID/locations/global/endpoints/openapi/chat/completions

google/gemini-3.1-flash-lite-preview.fallback.provider=azure
google/gemini-3.1-flash-lite-preview.fallback.model=gpt-4o-mini
google/gemini-3.1-flash-lite-preview.fallback.auth=apikey
google/gemini-3.1-flash-lite-preview.fallback.hostname=YOUR_AZURE_HOSTNAME
google/gemini-3.1-flash-lite-preview.fallback.url=/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview
google/gemini-3.1-flash-lite-preview.fallback.apikey=YOUR_API_KEY


## claude-sonnet-4-6
claude-sonnet-4-6.primary.provider=google
claude-sonnet-4-6.primary.model=claude-sonnet-4-6
claude-sonnet-4-6.primary.auth=oauth
claude-sonnet-4-6.primary.hostname=aiplatform.googleapis.com
claude-sonnet-4-6.primary.url=/v1/projects/YOUR_PROJECT_ID/locations/global/publishers/anthropic/models/claude-sonnet-4-6:streamRawPredict

claude-sonnet-4-6.fallback.provider=google
claude-sonnet-4-6.fallback.model=claude-sonnet-4-6
claude-sonnet-4-6.fallback.auth=oauth
claude-sonnet-4-6.fallback.hostname=aiplatform.googleapis.com
claude-sonnet-4-6.fallback.url=/v1/projects/YOUR_PROJECT_ID/locations/global/publishers/anthropic/models/claude-sonnet-4-6:streamRawPredict


## gpt-4.1-mini
gpt-4.1-mini.primary.provider=azure
gpt-4.1-mini.primary.model=gpt-4.1-mini
gpt-4.1-mini.primary.auth=apikey
gpt-4.1-mini.primary.hostname=YOUR_AZURE_HOSTNAME
gpt-4.1-mini.primary.url=/xxxopenai/deployments/gpt-4.1-mini/chat/completions?api-version=2025-01-01-preview
gpt-4.1-mini.primary.apikey=YOUR_API_KEY
gpt-4.1-mini.primary.targeturl=https://YOUR_AZURE_HOSTNAME/openai/deployments/gpt-4.1-mini/chat/completions?api-version=2025-01-01-preview

gpt-4.1-mini.fallback.provider=google
gpt-4.1-mini.fallback.model=google/gemini-3-flash-preview
gpt-4.1-mini.fallback.auth=apikey
gpt-4.1-mini.fallback.hostname=aiplatform.googleapis.com
gpt-4.1-mini.fallback.url=/v1/projects/YOUR_PROJECT_ID/locations/global/endpoints/openapi/chat/completions
gpt-4.1-mini.fallback.targeturl=https://aiplatform.googleapis.com/v1/projects/YOUR_PROJECT_ID/locations/global/endpoints/openapi/chat/completions

## gpt-4o-mini
gpt-4o-mini.primary.provider=azure
gpt-4o-mini.primary.model=gpt-4o-mini
gpt-4o-mini.primary.auth=apikey
gpt-4o-mini.primary.hostname=YOUR_AZURE_HOSTNAME
gpt-4o-mini.primary.url=/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview
gpt-4o-mini.primary.apikey=YOUR_API_KEY
gpt-4o-mini.primary.targeturl=https://YOUR_AZURE_HOSTNAME/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview

gpt-4o-mini.fallback.provider=azure
gpt-4o-mini.fallback.model=gpt-4o-mini
gpt-4o-mini.fallback.auth=apikey
gpt-4o-mini.fallback.hostname=YOUR_AZURE_HOSTNAME
gpt-4o-mini.fallback.url=/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview
gpt-4o-mini.fallback.apikey=YOUR_API_KEY
gpt-4o-mini.fallback.targeturl=https://YOUR_AZURE_HOSTNAME/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview
